# This is the configuration used to check the rubocop source code.
require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  Exclude:
    - db/**/*
    - "**/vendor/**/*"
    - public/**/*
    - log/**/*
    - tmp/**/*
    - app/assets/**/*

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'config/**/*.rb'
    - 'spec/**/*.rb'
    - 'test/**/*.rb'

Metrics/BlockNesting:
  Max: 10

Metrics/ClassLength:
  Max: 1000

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 1000

Metrics/PerceivedComplexity:
  Max: 12

Style/ClassAndModuleChildren:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'
